version: '2.1'

services:
  master:
    container_name: "${COMPOSE_PROJECT_NAME:-citus}_master"
    image: 'citusdata/citus:10.2.2'
    ports: ['5600:5432']
    labels: ['com.citusdata.role=Master']
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
  worker1:
    image: 'citusdata/citus:10.2.2'
    ports: ['5601:5432']
    labels: ['com.citusdata.role=Worker']
    depends_on: { manager: { condition: service_healthy } }
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
  worker2:
    image: 'citusdata/citus:10.2.2'
    ports: ['5602:5432']
    labels: ['com.citusdata.role=Worker']
    depends_on: { manager: { condition: service_healthy } }
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
  manager:
    container_name: "${COMPOSE_PROJECT_NAME:-citus}_manager"
    image: 'citusdata/membership-manager:0.2.0'
    volumes: ['/var/run/docker.sock:/var/run/docker.sock']
    depends_on: { master: { condition: service_healthy } }
