# Generated by Django 2.2.9 on 2020-01-28 08:53

from django.db import migrations, models
import django.db.models.deletion
import django_multitenant.fields

from django_multitenant.db import migrations as tenant_migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0016_auto_20191025_0844'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employees', db_constraint=False, to='tests.Account')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users_created', to='tests.Employee')),
            ],
        ),

        tenant_migrations.Distribute('Employee', reference=True),
    ]
