# Generated by Django 4.1.6 on 2023-02-16 17:12

import django.contrib.gis.db.models.fields
from django.contrib.gis.db import models
from django.db import migrations
import django.db.models.deletion
import django_multitenant.fields
import django_multitenant.mixins
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("tests", "0023_auto_20200412_0603"),
    ]

    from django.conf import settings

    if settings.USE_GIS:
        operations = [
            migrations.CreateModel(
                name="OrganizationLocation",
                fields=[
                    (
                        "id",
                        models.UUIDField(
                            default=uuid.uuid4,
                            editable=False,
                            primary_key=True,
                            serialize=False,
                        ),
                    ),
                    (
                        "location",
                        django.contrib.gis.db.models.fields.PointField(srid=4326),
                    ),
                    (
                        "organization",
                        models.ForeignKey(
                            on_delete=django.db.models.deletion.CASCADE,
                            to="tests.Organization",
                        ),
                    ),
                ],
                options={
                    "abstract": False,
                },
                bases=(
                    django_multitenant.mixins.TenantModelMixin,
                    django.contrib.gis.db.models.Model,
                ),
            ),
        ]
