# Generated by Django 4.1 on 2023-02-23 17:24

from django.db import migrations
from django_multitenant.db import migrations as tenant_migrations


class Migration(migrations.Migration):
    dependencies = [
        ("tests", "0026_product_purchase_store_alter_account_id_and_more"),
    ]
    operations = []

    operations += [
        # Drop constraints
        migrations.RunSQL(
            "ALTER TABLE tests_store DROP CONSTRAINT tests_store_pkey CASCADE;"
        ),
        migrations.RunSQL(
            "ALTER TABLE tests_product DROP CONSTRAINT tests_product_pkey CASCADE;"
        ),
        migrations.RunSQL(
            "ALTER TABLE tests_purchase DROP CONSTRAINT tests_purchase_pkey CASCADE;"
        ),
        migrations.RunSQL(
            "ALTER TABLE tests_transaction DROP CONSTRAINT tests_transaction_pkey CASCADE;"
        ),
    ]

    operations += [
        tenant_migrations.Distribute("Staff", reference=True),
        tenant_migrations.Distribute("Store"),
        tenant_migrations.Distribute("Product"),
        tenant_migrations.Distribute("Purchase"),
        tenant_migrations.Distribute("Transaction"),
    ]

    operations += [
        migrations.RunSQL(
            "ALTER TABLE tests_store ADD CONSTRAINT tests_store_pkey PRIMARY KEY (id);"
        ),
        migrations.RunSQL(
            "ALTER TABLE tests_product ADD CONSTRAINT tests_product_pkey PRIMARY KEY (store_id, id);"
        ),
        migrations.RunSQL(
            "ALTER TABLE tests_purchase ADD CONSTRAINT tests_purchase_pkey PRIMARY KEY (store_id, id);"
        ),
        migrations.RunSQL(
            "ALTER TABLE tests_transaction ADD CONSTRAINT tests_transaction_pkey PRIMARY KEY (store_id, id);"
        ),
    ]
