# Generated by Django 4.1 on 2023-03-13 07:43

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("tests", "0027_many_to_many_distribute"),
    ]

    operations = [
        migrations.AddField(
            model_name="store",
            name="store_users",
            field=models.ManyToManyField(
                blank=True, related_name="users", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
