# Generated by Django 4.1.7 on 2023-03-18 11:03

from django.db import migrations, models
import django_multitenant.fields
import django_multitenant.mixins
import django_multitenant.models


class Migration(migrations.Migration):
    dependencies = [
        ("tests", "0027_many_to_many_distribute"),
    ]

    operations = [
        migrations.CreateModel(
            name="MigrationUseInMigrationsModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
            ],
            options={
                "abstract": False,
            },
            bases=(django_multitenant.mixins.TenantModelMixin, models.Model),
            managers=[
                ("objects", django_multitenant.models.TenantManager()),
            ],
        ),
        migrations.AlterModelManagers(
            name="account",
            managers=[
                ("objects", django_multitenant.models.TenantManager()),
            ],
        ),
        migrations.AlterModelManagers(
            name="aliasedtask",
            managers=[
                ("objects", django_multitenant.models.TenantManager()),
            ],
        ),
        migrations.AlterModelManagers(
            name="business",
            managers=[
                ("objects", django_multitenant.models.TenantManager()),
            ],
        ),
        migrations.AlterModelManagers(
            name="manager",
            managers=[
                ("objects", django_multitenant.models.TenantManager()),
            ],
        ),
        migrations.AlterModelManagers(
            name="migrationtestmodel",
            managers=[
                ("objects", django_multitenant.models.TenantManager()),
            ],
        ),
        migrations.AlterModelManagers(
            name="modelconfig",
            managers=[
                ("objects", django_multitenant.models.TenantManager()),
            ],
        ),
        migrations.AlterModelManagers(
            name="organization",
            managers=[
                ("objects", django_multitenant.models.TenantManager()),
            ],
        ),
        migrations.AlterModelManagers(
            name="product",
            managers=[
                ("objects", django_multitenant.models.TenantManager()),
            ],
        ),
        migrations.AlterModelManagers(
            name="project",
            managers=[
                ("objects", django_multitenant.models.TenantManager()),
            ],
        ),
        migrations.AlterModelManagers(
            name="projectmanager",
            managers=[
                ("objects", django_multitenant.models.TenantManager()),
            ],
        ),
        migrations.AlterModelManagers(
            name="purchase",
            managers=[
                ("objects", django_multitenant.models.TenantManager()),
            ],
        ),
        migrations.AlterModelManagers(
            name="record",
            managers=[
                ("objects", django_multitenant.models.TenantManager()),
            ],
        ),
        migrations.AlterModelManagers(
            name="revenue",
            managers=[
                ("objects", django_multitenant.models.TenantManager()),
            ],
        ),
        migrations.AlterModelManagers(
            name="somerelatedmodel",
            managers=[
                ("objects", django_multitenant.models.TenantManager()),
            ],
        ),
        migrations.AlterModelManagers(
            name="store",
            managers=[
                ("objects", django_multitenant.models.TenantManager()),
            ],
        ),
        migrations.AlterModelManagers(
            name="subtask",
            managers=[
                ("objects", django_multitenant.models.TenantManager()),
            ],
        ),
        migrations.AlterModelManagers(
            name="template",
            managers=[
                ("objects", django_multitenant.models.TenantManager()),
            ],
        ),
        migrations.AlterModelManagers(
            name="tenant",
            managers=[
                ("objects", django_multitenant.models.TenantManager()),
            ],
        ),
        migrations.AlterModelManagers(
            name="tenantnotidmodel",
            managers=[
                ("objects", django_multitenant.models.TenantManager()),
            ],
        ),
        migrations.AlterModelManagers(
            name="transaction",
            managers=[
                ("objects", django_multitenant.models.TenantManager()),
            ],
        ),
    ]
