# Generated by Django 4.1.6 on 2023-02-16 17:12

import django_multitenant.fields
import django_multitenant.mixins

from django.db import migrations
from django.conf import settings
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("tests", "0030_store_user_alter_account_id_alter_aliasedtask_id_and_more"),
    ]

    if settings.USE_GIS:
        import django.contrib.gis.db.models.fields
        from django.contrib.gis.db import models

        operations = [
            migrations.CreateModel(
                name="OrganizationLocation",
                fields=[
                    (
                        "id",
                        models.UUIDField(
                            default=uuid.uuid4,
                            editable=False,
                            primary_key=True,
                            serialize=False,
                        ),
                    ),
                    (
                        "location",
                        django.contrib.gis.db.models.fields.PointField(srid=4326),
                    ),
                    (
                        "organization",
                        django_multitenant.fields.TenantForeignKey(
                            on_delete=django.db.models.deletion.CASCADE,
                            to="tests.Organization",
                        ),
                    ),
                ],
                options={
                    "abstract": False,
                },
                bases=(
                    django_multitenant.mixins.TenantModelMixin,
                    models.Model,
                ),
            ),
        ]
