# Generated by Django 4.2 on 2023-04-04 16:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tests", "0030_store_user_alter_account_id_alter_aliasedtask_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transaction",
            name="date",
            field=models.DateField(auto_now_add=True),
        ),
    ]
