# Generated by Django 4.1.7 on 2023-03-18 08:00

from django.db import migrations
# from ..models import MigrationUseInMigrationsModel
import inspect


def empty_users(apps, schema_editor):

    MigrationUseInMigrationsModel = apps.get_model("tests", "MigrationUseInMigrationsModel")
    print(
        "Used Manager:",
        type(MigrationUseInMigrationsModel.objects),
    )
    base_classes = inspect.getmro(MigrationUseInMigrationsModel) 
    print("Base classes:",base_classes)
    
    MigrationUseInMigrationsModel.objects.create(name="test", pk=1)


class Migration(migrations.Migration):

    dependencies = [
        ("tests", "0028_migrationuseinmigrationsmodel_alter_account_managers_and_more"),
    ]

    operations = [
        migrations.RunPython(empty_users),
    ]
